# argdist-bpfcc
# Autogenerated from man page /usr/share/man/man8/argdist-bpfcc.8.gz
complete -c argdist-bpfcc -s h -d 'Print usage message'
complete -c argdist-bpfcc -s p -d 'Trace only functions in the process PID'
complete -c argdist-bpfcc -s z -d 'When collecting string arguments (of type char*), collect up to STRING_SIZE  …'
complete -c argdist-bpfcc -s i -d 'Print the collected data every INTERVAL seconds.  The default is 1 second'
complete -c argdist-bpfcc -s d -d 'Total duration of trace in seconds'
complete -c argdist-bpfcc -s n -d 'Print the collected data COUNT times and then exit'
complete -c argdist-bpfcc -s v -d 'Display the generated BPF program, for debugging purposes'
complete -c argdist-bpfcc -s T -d 'When collecting frequency counts, display only the top TOP entries'
complete -c argdist-bpfcc -s H -s C -d 'One or more probe specifications that instruct argdist which functions to pro…'
complete -c argdist-bpfcc -s I -d 'One or more header files that should be included in the BPF program'

