# bashreadline-bpfcc
# Autogenerated from man page /usr/share/man/man8/bashreadline-bpfcc.8.gz
complete -c bashreadline-bpfcc -s h -d 'Print usage message'
complete -c bashreadline-bpfcc -s s -d 'Specify the location of libreadline'

