# bindsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/bindsnoop-bpfcc.8.gz
complete -c bindsnoop-bpfcc -s h -l help
complete -c bindsnoop-bpfcc -s t -l timestamp
complete -c bindsnoop-bpfcc -s w -l wide
complete -c bindsnoop-bpfcc -s p -l pid
complete -c bindsnoop-bpfcc -s P -l port
complete -c bindsnoop-bpfcc -l cgroupmap
complete -c bindsnoop-bpfcc -l mntnsmap
complete -c bindsnoop-bpfcc -s E -l errors
complete -c bindsnoop-bpfcc -s U -l print-uid
complete -c bindsnoop-bpfcc -s u -l uid
complete -c bindsnoop-bpfcc -l count -d 'EXAMPLES: Trace all IPv4 and IPv6 bind()s bindsnoop'

