# biolatency-bpfcc
# Autogenerated from man page /usr/share/man/man8/biolatency-bpfcc.8.gz
complete -c biolatency-bpfcc -s T -d 'Include timestamps on output'
complete -c biolatency-bpfcc -s m -d 'Output histogram in milliseconds'
complete -c biolatency-bpfcc -s D -d 'Print a histogram per disk device'
complete -c biolatency-bpfcc -s F -d 'Print a histogram per set of I/O flags'
complete -c biolatency-bpfcc -s j -d 'Print a histogram dictionary'
complete -c biolatency-bpfcc -s h -d 'Print usage message'

