# biolatpcts-bpfcc
# Autogenerated from man page /usr/share/man/man8/biolatpcts-bpfcc.8.gz
complete -c biolatpcts-bpfcc -s i -l interval -d 'Report interval.  (default: 3)'
complete -c biolatpcts-bpfcc -s w -l which -d 'Which latency to measure.  (default: on-device)'
complete -c biolatpcts-bpfcc -s p -l pcts -d 'Percentiles to calculate.  (default: 1,5,10,16,25,50,75,84,90,95,99,100)'
complete -c biolatpcts-bpfcc -s j -l json -d 'Output in json'
complete -c biolatpcts-bpfcc -s v -l verbose -d 'Enable debug output'
complete -c biolatpcts-bpfcc -s h -d 'Print usage message'

