# biosnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/biosnoop-bpfcc.8.gz
complete -c biosnoop-bpfcc -s h -d 'Print usage message'
complete -c biosnoop-bpfcc -s Q -d 'Include a column showing the time spent quueued in the OS.  EXAMPLES'

