# biotop-bpfcc
# Autogenerated from man page /usr/share/man/man8/biotop-bpfcc.8.gz
complete -c biotop-bpfcc -s C -d 'Don\'t clear the screen'
complete -c biotop-bpfcc -s r -d 'Maximum number of rows to print.  Default is 20'

