# bpflist-bpfcc
# Autogenerated from man page /usr/share/man/man8/bpflist-bpfcc.8.gz
complete -c bpflist-bpfcc -s h -d 'Print usage message'
complete -c bpflist-bpfcc -s v -d 'Count kprobes and uprobes as well as BPF programs'

