# btrfsslower-bpfcc
# Autogenerated from man page /usr/share/man/man8/btrfsslower-bpfcc.8.gz
complete -c btrfsslower-bpfcc -s p -d 'Trace this PID only'
complete -c btrfsslower-bpfcc -s d -d 'Total duration of trace in seconds.  EXAMPLES'

