# capable-bpfcc
# Autogenerated from man page /usr/share/man/man8/capable-bpfcc.8.gz
complete -c capable-bpfcc -s v -d 'Include non-audit capability checks'
complete -c capable-bpfcc -s K -d 'Include kernel stack traces to the output'
complete -c capable-bpfcc -s U -d 'Include user-space stack traces to the output'
complete -c capable-bpfcc -s x -d 'Show extra fields in TID and INSETID columns'
complete -c capable-bpfcc -l cgroupmap -d 'Trace cgroups in this BPF map only (filtered in-kernel)'
complete -c capable-bpfcc -l mntnsmap -d 'Trace mount namespaces in this BPF map only (filtered in-kernel)'
complete -c capable-bpfcc -s h -d 'USAGE message'
complete -c capable-bpfcc -l unique -d 'Don\'t repeat stacks for the same PID or cgroup.  EXAMPLES'

