# cjet
# Autogenerated from man page /usr/share/man/man1/cjet.1.gz
complete -c cjet -s h -d 'Show summary of options'
complete -c cjet -s f -d 'Use full paint mode instead of partial paint mode'
complete -c cjet -s p -d 'Ignore paper size commands'
complete -c cjet -s q -d 'Quiet mode.  Suppresses all warning messages'
complete -c cjet -s x -d 'Shift output on paper by X dots horizontally'
complete -c cjet -s y -d 'Shift output on paper by Y dots vertically'

