# compactsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/compactsnoop-bpfcc.8.gz
complete -c compactsnoop-bpfcc -s h -d 'Print usage message'
complete -c compactsnoop-bpfcc -s T -d 'Include a timestamp column'
complete -c compactsnoop-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c compactsnoop-bpfcc -s d -d 'Total duration of trace in seconds'
complete -c compactsnoop-bpfcc -s K -d 'Output kernel stack trace'
complete -c compactsnoop-bpfcc -s e -d 'Show extended fields.  EXAMPLES'

