# cpudist-bpfcc
# Autogenerated from man page /usr/share/man/man8/cpudist-bpfcc.8.gz
complete -c cpudist-bpfcc -s h -d 'Print usage message'
complete -c cpudist-bpfcc -s O -d 'Measure off-CPU time instead of on-CPU time'
complete -c cpudist-bpfcc -s T -d 'Include timestamps on output'
complete -c cpudist-bpfcc -s m -d 'Output histogram in milliseconds'
complete -c cpudist-bpfcc -s P -d 'Print a histogram for each PID (tgid from the kernel\'s perspective)'
complete -c cpudist-bpfcc -s L -d 'Print a histogram for each TID (pid from the kernel\'s perspective)'
complete -c cpudist-bpfcc -s p -d 'Only show this PID (filtered in kernel for efficiency)'

