# criticalstat-bpfcc
# Autogenerated from man page /usr/share/man/man8/criticalstat-bpfcc.8.gz
complete -c criticalstat-bpfcc -s h -d 'Print usage message'
complete -c criticalstat-bpfcc -s p -d 'Find long sections where preemption was disabled on local CPU'
complete -c criticalstat-bpfcc -s i -d 'Find long sections where interrupt was disabled on local CPU'
complete -c criticalstat-bpfcc -s d -d 'Only identify sections that are longer than DURATION in microseconds'

