# cryptsetup-ssh
# Autogenerated from man page /usr/share/man/man8/cryptsetup-ssh.8.gz
complete -c cryptsetup-ssh -l debug -d 'Show debug messages'
complete -c cryptsetup-ssh -l debug-json -d 'Show debug messages including JSON metadata'
complete -c cryptsetup-ssh -s v -l verbose -d 'Shows more detailed error messages'
complete -c cryptsetup-ssh -s '?' -l help -d 'Show help'
complete -c cryptsetup-ssh -l key-slot -d 'Keyslot to assign the token to'
complete -c cryptsetup-ssh -l ssh-keypath -d 'Path to the SSH key for connecting to the remote server'
complete -c cryptsetup-ssh -l ssh-path -d 'Path to the key file on the remote server'
complete -c cryptsetup-ssh -l ssh-server -d 'IP address/URL of the remote server for this token'
complete -c cryptsetup-ssh -l ssh-user -d 'are required for this operation'
complete -c cryptsetup-ssh -s V -l version -d 'Print program version NOTES The information provided when adding the token (S…'

