# cthreads-bpfcc
# Autogenerated from man page /usr/share/man/man8/cthreads-bpfcc.8.gz
complete -c cthreads-bpfcc -s l -d 'The language to trace'
complete -c cthreads-bpfcc -s v -d 'Print the resulting BPF program, for debugging purposes'

