# dbslower-bpfcc
# Autogenerated from man page /usr/share/man/man8/dbslower-bpfcc.8.gz
complete -c dbslower-bpfcc -s p -d 'Trace this PID'
complete -c dbslower-bpfcc -s x -d 'Path to MySQL binary'
complete -c dbslower-bpfcc -s m -d 'Minimum query latency (duration) to trace, in milliseconds.  Default is 1 ms'
complete -c dbslower-bpfcc -s h -d 'Print usage message'

