# dbstat-bpfcc
# Autogenerated from man page /usr/share/man/man8/dbstat-bpfcc.8.gz
complete -c dbstat-bpfcc -s p -d 'Trace this PID'
complete -c dbstat-bpfcc -s m -d 'Minimum query latency (duration) to trace, in milliseconds'
complete -c dbstat-bpfcc -s u -d 'Display query latencies in microseconds (default: milliseconds)'
complete -c dbstat-bpfcc -s i -d 'Print summaries (histograms) at this interval, specified in seconds'
complete -c dbstat-bpfcc -s h -d 'Print usage message'

