# dcsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/dcsnoop-bpfcc.8.gz
complete -c dcsnoop-bpfcc -s h -d 'Print usage message'
complete -c dcsnoop-bpfcc -s a -d 'Trace references, not just failed lookups.  EXAMPLES'

