# deadlock-bpfcc
# Autogenerated from man page /usr/share/man/man8/deadlock-bpfcc.8.gz
complete -c deadlock-bpfcc -s h -l help -d 'show this help message and exit'
complete -c deadlock-bpfcc -l binary -d 'If set, trace the mutexes from the binary at this path'
complete -c deadlock-bpfcc -l dump-graph -d 'If set, this will dump the mutex graph to the specified file'
complete -c deadlock-bpfcc -l verbose -d 'Print statistics about the mutex wait graph'
complete -c deadlock-bpfcc -l lock-symbols -d 'Comma-separated list of lock symbols to trace.  Default is pthread_mutex_lock'
complete -c deadlock-bpfcc -l unlock-symbols -d 'Comma-separated list of unlock symbols to trace'
complete -c deadlock-bpfcc -l unlock_symbols -d 'OUTPUT This program does not output any fields'

