# dirtop-bpfcc
# Autogenerated from man page /usr/share/man/man8/dirtop-bpfcc.8.gz
complete -c dirtop-bpfcc -s d -d 'Defines a list of directories, comma separated, to observe'
complete -c dirtop-bpfcc -s C -d 'Don\'t clear the screen'
complete -c dirtop-bpfcc -s r -d 'Maximum number of rows to print.  Default is 20'
complete -c dirtop-bpfcc -s s -d 'Sort column.  Default is rbytes (read throughput)'
complete -c dirtop-bpfcc -s p -d 'Trace this PID only'

