# dislocker-find
# Autogenerated from man page /usr/share/man/man1/dislocker-find.1.gz
complete -c dislocker-find -s h -d 'print the help and exit . PP'
complete -c dislocker-find -s 1 -d 'EXAMPLES No volume is found automatically, the program returns 0 volume found…'

