# dislocker-bek
# Autogenerated from man page /usr/share/man/man1/dislocker-bek.1.gz
complete -c dislocker-bek -s h -d 'print all options to help'
complete -c dislocker-bek -s f -d 'read information about a '

