# dislocker-metadata
# Autogenerated from man page /usr/share/man/man1/dislocker-metadata.1.gz
complete -c dislocker-metadata -s h -d 'print all options to help'
complete -c dislocker-metadata -s o -d 'partition offset'
complete -c dislocker-metadata -s v -d 'increase verbosity to debug level'
complete -c dislocker-metadata -s V -d 'volume to get metadata from AUTHOR The DISLOCKER was written by Romain Coltel…'

