# dpkg-mergechangelogs
# Autogenerated from man page /usr/share/man/man1/dpkg-mergechangelogs.1.gz
complete -c dpkg-mergechangelogs -l merge-unreleased -d 'Ignore the version number when the entries are marked as \\s-1UNRELEASED\\s0 (s…'
complete -c dpkg-mergechangelogs -s m -l merge-prereleases -d 'Drop the part after the last tilde in the version number when doing version c…'
complete -c dpkg-mergechangelogs -l help -d 'Show the usage message and exit'

