# drsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/drsnoop-bpfcc.8.gz
complete -c drsnoop-bpfcc -s h -d 'Print usage message'
complete -c drsnoop-bpfcc -s T -d 'Include a timestamp column'
complete -c drsnoop-bpfcc -s U -d 'Show UID'
complete -c drsnoop-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c drsnoop-bpfcc -s t -d 'Trace this thread ID only (filtered in-kernel)'
complete -c drsnoop-bpfcc -s u -d 'Trace this UID only (filtered in-kernel)'
complete -c drsnoop-bpfcc -s d -d 'Total duration of trace in seconds'
complete -c drsnoop-bpfcc -s n -d 'Only print processes where its name partially matches \'name\''
complete -c drsnoop-bpfcc -s v -d 'Run in verbose mode.  Will output system memory state EXAMPLES'

