# exitsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/exitsnoop-bpfcc.8.gz
complete -c exitsnoop-bpfcc -s h -d 'Print usage message'
complete -c exitsnoop-bpfcc -s t -d 'Include a timestamp column'
complete -c exitsnoop-bpfcc -l utc -d 'Include a timestamp column, use UTC timezone'
complete -c exitsnoop-bpfcc -s x -d 'Exclude successful exits, exit( 0 )'
complete -c exitsnoop-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c exitsnoop-bpfcc -l label -d 'Label each line with LABEL (default \'exit\') in first column (2nd if timestamp…'
complete -c exitsnoop-bpfcc -l per-thread -d 'Trace per thread termination EXAMPLES'

