# filetop-bpfcc
# Autogenerated from man page /usr/share/man/man8/filetop-bpfcc.8.gz
complete -c filetop-bpfcc -s a -d 'Include non-regular file types (sockets, FIFOs, etc)'
complete -c filetop-bpfcc -s C -d 'Don\'t clear the screen'
complete -c filetop-bpfcc -s r -d 'Maximum number of rows to print.  Default is 20'
complete -c filetop-bpfcc -s s -d 'Sort column.  Default is rbytes (read throughput)'
complete -c filetop-bpfcc -s p -d 'Trace this PID only'

