# fileslower-bpfcc
# Autogenerated from man page /usr/share/man/man8/fileslower-bpfcc.8.gz
complete -c fileslower-bpfcc -s a -d 'Include non-regular file types in output (sockets, FIFOs, etc)'
complete -c fileslower-bpfcc -s p -d 'Trace this PID only'

