# filelife-bpfcc
# Autogenerated from man page /usr/share/man/man8/filelife-bpfcc.8.gz
complete -c filelife-bpfcc -s h -d 'Print usage message'
complete -c filelife-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel).  EXAMPLES'

