# funcinterval-bpfcc
# Autogenerated from man page /usr/share/man/man8/funcinterval-bpfcc.8.gz
complete -c funcinterval-bpfcc -s p -d 'Trace this process ID only'
complete -c funcinterval-bpfcc -s i -d 'Print output every interval seconds'
complete -c funcinterval-bpfcc -s d -d 'Total duration of trace, in seconds'
complete -c funcinterval-bpfcc -s T -d 'Include timestamps on output'
complete -c funcinterval-bpfcc -s u -d 'Output histogram in microseconds'
complete -c funcinterval-bpfcc -s m -d 'Output histogram in milliseconds'
complete -c funcinterval-bpfcc -s h -d 'Print usage message'
complete -c funcinterval-bpfcc -s v -d 'Print the BPF program (for debugging purposes).  EXAMPLES'

