# funclatency-bpfcc
# Autogenerated from man page /usr/share/man/man8/funclatency-bpfcc.8.gz
complete -c funclatency-bpfcc -s p -d 'Trace this process ID only'
complete -c funclatency-bpfcc -s i -d 'Print output every interval seconds'
complete -c funclatency-bpfcc -s d -d 'Total duration of trace, in seconds'
complete -c funclatency-bpfcc -s T -d 'Include timestamps on output'
complete -c funclatency-bpfcc -s u -d 'Output histogram in microseconds'
complete -c funclatency-bpfcc -s m -d 'Output histogram in milliseconds'
complete -c funclatency-bpfcc -s F -d 'Print a separate histogram per function matched'
complete -c funclatency-bpfcc -s r -d 'Use regular expressions for the search pattern'
complete -c funclatency-bpfcc -s h -d 'Print usage message'
complete -c funclatency-bpfcc -s v -d 'Print the BPF program (for debugging purposes).  EXAMPLES'

