# funccount-bpfcc
# Autogenerated from man page /usr/share/man/man8/funccount-bpfcc.8.gz
complete -c funccount-bpfcc -s h -d 'Print usage message'
complete -c funccount-bpfcc -s p -d 'Trace this process ID only'
complete -c funccount-bpfcc -s i -d 'Print output every interval seconds'
complete -c funccount-bpfcc -s d -d 'Total duration of trace in seconds'
complete -c funccount-bpfcc -s T -d 'Include timestamps on output'
complete -c funccount-bpfcc -s r -d 'Use regular expressions for the search pattern'
complete -c funccount-bpfcc -s D -d 'Print the BPF program before starting (for debugging purposes)'
complete -c funccount-bpfcc -s c -d 'Trace on this CPU only.  EXAMPLES'

