# funcslower-bpfcc
# Autogenerated from man page /usr/share/man/man8/funcslower-bpfcc.8.gz
complete -c funcslower-bpfcc -s m -d 'Minimum duration to trace, in milliseconds.  Default is 1 ms'
complete -c funcslower-bpfcc -s u -d 'Minimum duration to trace, in microseconds'
complete -c funcslower-bpfcc -s a -d 'Print the function\'s arguments, up to 6'
complete -c funcslower-bpfcc -s T -d 'Print a HH:MM:SS timestamp with each entry'
complete -c funcslower-bpfcc -s t -d 'Print a seconds timestamp with each entry, at microsecond resolution'
complete -c funcslower-bpfcc -s f -d 'Print output in folded stack format'
complete -c funcslower-bpfcc -s U -d 'Show stacks from user space only (no kernel space stacks)'
complete -c funcslower-bpfcc -s K -d 'Show stacks from kernel space only (no user space stacks)'
complete -c funcslower-bpfcc -s v -d 'Print the resulting BPF program, for debugging purposes'
complete -c funcslower-bpfcc -s p -d 'Trace this PID only'

