# gdm-screenshot
# Autogenerated from man page /usr/share/man/man1/gdm-screenshot.1.gz
complete -c gdm-screenshot -s h -l help -d 'Show help options'
complete -c gdm-screenshot -l help-all -d 'Show all help options'
complete -c gdm-screenshot -l help-gtk -d 'Show \\s-1GTK+\\s0 Options . PP Application Options:'
complete -c gdm-screenshot -s d -l debug -d 'Debugging output'

