# gdmflexiserver
# Autogenerated from man page /usr/share/man/man1/gdmflexiserver.1.gz
complete -c gdmflexiserver -s h -l help -d 'Show help options'
complete -c gdmflexiserver -l help-all -d 'Show all help options'
complete -c gdmflexiserver -l help-gtk -d 'Show \\s-1GTK+\\s0 Options . PP Application Options:'
complete -c gdmflexiserver -s d -l debug -d 'Debugging output'

