# gnome-character-map
# Autogenerated from man page /usr/share/man/man1/gnome-character-map.1.gz
complete -c gnome-character-map -l font -d 'Font to start with, ex: \'Serif 27\''
complete -c gnome-character-map -l display -d 'X display to use'

