# gucharmap
# Autogenerated from man page /usr/share/man/man1/gucharmap.1.gz
complete -c gucharmap -l font -d 'Font to start with, ex: \'Serif 27\''
complete -c gucharmap -l display -d 'X display to use'

