# hardirqs-bpfcc
# Autogenerated from man page /usr/share/man/man8/hardirqs-bpfcc.8.gz
complete -c hardirqs-bpfcc -s h -d 'Print usage message'
complete -c hardirqs-bpfcc -s T -d 'Include timestamps on output'
complete -c hardirqs-bpfcc -s N -d 'Output in nanoseconds'
complete -c hardirqs-bpfcc -s C -d 'Count events only'
complete -c hardirqs-bpfcc -s d -d 'Show IRQ time distribution as histograms.  EXAMPLES'

