# inject-bpfcc
# Autogenerated from man page /usr/share/man/man8/inject-bpfcc.8.gz
complete -c inject-bpfcc -s h -d 'Print usage message'
complete -c inject-bpfcc -s v -d 'Display the generated BPF program, for debugging or modification'
complete -c inject-bpfcc -s I -d 'Necessary headers to be included'
complete -c inject-bpfcc -s P -d 'Optional probability of failure, default 1'
complete -c inject-bpfcc -s c -d 'Number of errors to inject before stopping, default never stops'

