# javastat-bpfcc
# Autogenerated from man page /usr/share/man/man8/javastat-bpfcc.8.gz
complete -c javastat-bpfcc -s l -d 'The language to trace.  By default, all languages are traced'
complete -c javastat-bpfcc -s C -d 'Do not clear the screen between updates'
complete -c javastat-bpfcc -s S -d 'Sort the output by the specified field'
complete -c javastat-bpfcc -s r -d 'Do not print more than this number of rows'
complete -c javastat-bpfcc -s d -d 'Print the resulting BPF program, for debugging purposes'

