# javaflow-bpfcc
# Autogenerated from man page /usr/share/man/man8/javaflow-bpfcc.8.gz
complete -c javaflow-bpfcc -s M -d 'Print only method calls where the method name begins with this string'
complete -c javaflow-bpfcc -s C -d 'Print only method calls where the class name begins with this string'
complete -c javaflow-bpfcc -s v -d 'Print the resulting BPF program, for debugging purposes'

