# javathreads-bpfcc
# Autogenerated from man page /usr/share/man/man8/javathreads-bpfcc.8.gz
complete -c javathreads-bpfcc -s l -d 'The language to trace'
complete -c javathreads-bpfcc -s v -d 'Print the resulting BPF program, for debugging purposes'

