# join-dctrl
# Autogenerated from man page /usr/share/man/man1/join-dctrl.1.gz
complete -c join-dctrl -s 1 -l 1st-join-field -d 'Specify the join  field of the first input file'
complete -c join-dctrl -s 2 -l 2nd-join-field -d 'Specify the join  field of the second input file'
complete -c join-dctrl -s j -l join-field -d 'Specify a common join  field for all files'
complete -c join-dctrl -s a -l unpairable-from -d 'Specify that unmatched paragraphs from the first (if  1 is given) or the seco…'
complete -c join-dctrl -s o -l output-fields -d 'Specify which fields are included in the output'
complete -c join-dctrl -s l -l errorlevel -d 'Set log level to R level '
complete -c join-dctrl -s V -l version -d 'Print out version information'
complete -c join-dctrl -s C -l copying -d 'Print out the copyright license'
complete -c join-dctrl -s h -l help -d 'Print out a help summary'

