# killsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/killsnoop-bpfcc.8.gz
complete -c killsnoop-bpfcc -s h -d 'Print usage message'
complete -c killsnoop-bpfcc -s x -d 'Only print failed kill() syscalls'
complete -c killsnoop-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c killsnoop-bpfcc -s s -d 'Trace this signal only (filtered in-kernel).  EXAMPLES'

