# klockstat-bpfcc
# Autogenerated from man page /usr/share/man/man8/klockstat-bpfcc.8.gz
complete -c klockstat-bpfcc -s h -d 'Print usage message'
complete -c klockstat-bpfcc -s i -d 'print summary at this interval (seconds)'
complete -c klockstat-bpfcc -s c -d 'print locks taken by given caller filter (e. g. , pipe_)'
complete -c klockstat-bpfcc -s S -d 'sort data on specific columns defined by FIELDS string (by default the data i…'
complete -c klockstat-bpfcc -s n -d 'print COUNT number of locks'
complete -c klockstat-bpfcc -s s -d 'print COUNT number of stack entries'
complete -c klockstat-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c klockstat-bpfcc -s t -d 'Trace this thread ID only (filtered in-kernel)'
complete -c klockstat-bpfcc -s d -d 'Total duration of trace in seconds'
complete -c klockstat-bpfcc -l stack-storage-size -d 'Change the number of unique stack traces that can be stored and displayed'

