# llcstat-bpfcc
# Autogenerated from man page /usr/share/man/man8/llcstat-bpfcc.8.gz
complete -c llcstat-bpfcc -s h -d 'Print usage message'
complete -c llcstat-bpfcc -s c -d 'Sample one in this many cache reference and cache miss events'

