# lvm-dumpconfig
# Autogenerated from man page /usr/share/man/man8/lvm-dumpconfig.8.gz
complete -c lvm-dumpconfig -l atversion
complete -c lvm-dumpconfig -l commandprofile
complete -c lvm-dumpconfig -l config
complete -c lvm-dumpconfig -s d -l debug
complete -c lvm-dumpconfig -l driverloaded
complete -c lvm-dumpconfig -s f -l file
complete -c lvm-dumpconfig -s h -l help
complete -c lvm-dumpconfig -l ignoreadvanced
complete -c lvm-dumpconfig -l ignorelocal
complete -c lvm-dumpconfig -l ignoreunsupported
complete -c lvm-dumpconfig -s l -l list
complete -c lvm-dumpconfig -l lockopt
complete -c lvm-dumpconfig -l longhelp
complete -c lvm-dumpconfig -l mergedconfig
complete -c lvm-dumpconfig -l metadataprofile
complete -c lvm-dumpconfig -l nolocking
complete -c lvm-dumpconfig -l profile
complete -c lvm-dumpconfig -s q -l quiet
complete -c lvm-dumpconfig -l showdeprecated
complete -c lvm-dumpconfig -l showunsupported
complete -c lvm-dumpconfig -l sinceversion
complete -c lvm-dumpconfig -s t -l test
complete -c lvm-dumpconfig -l typeconfig
complete -c lvm-dumpconfig -l unconfigured
complete -c lvm-dumpconfig -l validate
complete -c lvm-dumpconfig -s v -l verbose
complete -c lvm-dumpconfig -l version
complete -c lvm-dumpconfig -l withcomments
complete -c lvm-dumpconfig -l withgeneralpreamble
complete -c lvm-dumpconfig -l withlocalpreamble
complete -c lvm-dumpconfig -l withspaces
complete -c lvm-dumpconfig -l withsummary
complete -c lvm-dumpconfig -l withversions
complete -c lvm-dumpconfig -s y -l yes

