# lvm-config
# Autogenerated from man page /usr/share/man/man8/lvm-config.8.gz
complete -c lvm-config -l atversion
complete -c lvm-config -l commandprofile
complete -c lvm-config -l config
complete -c lvm-config -s d -l debug
complete -c lvm-config -l driverloaded
complete -c lvm-config -s f -l file
complete -c lvm-config -s h -l help
complete -c lvm-config -l ignoreadvanced
complete -c lvm-config -l ignorelocal
complete -c lvm-config -l ignoreunsupported
complete -c lvm-config -s l -l list
complete -c lvm-config -l lockopt
complete -c lvm-config -l longhelp
complete -c lvm-config -l mergedconfig
complete -c lvm-config -l metadataprofile
complete -c lvm-config -l nolocking
complete -c lvm-config -l profile
complete -c lvm-config -s q -l quiet
complete -c lvm-config -l showdeprecated
complete -c lvm-config -l showunsupported
complete -c lvm-config -l sinceversion
complete -c lvm-config -s t -l test
complete -c lvm-config -l typeconfig
complete -c lvm-config -l unconfigured
complete -c lvm-config -l validate
complete -c lvm-config -s v -l verbose
complete -c lvm-config -l version
complete -c lvm-config -l withcomments
complete -c lvm-config -l withgeneralpreamble
complete -c lvm-config -l withlocalpreamble
complete -c lvm-config -l withspaces
complete -c lvm-config -l withsummary
complete -c lvm-config -l withversions
complete -c lvm-config -s y -l yes

