# memleak-bpfcc
# Autogenerated from man page /usr/share/man/man8/memleak-bpfcc.8.gz
complete -c memleak-bpfcc -s h -d 'Print usage message'
complete -c memleak-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel).  This traces libc allocator'
complete -c memleak-bpfcc -s t -d 'Print a trace of all allocation and free requests and results'
complete -c memleak-bpfcc -s a -d 'Print a list of allocations that weren\'t freed (and their sizes) in addition …'
complete -c memleak-bpfcc -s o -d 'Print only allocations older than OLDER milliseconds'
complete -c memleak-bpfcc -s c -d 'Run the specified command and trace its allocations only'
complete -c memleak-bpfcc -l combined-only -d 'Use statistics precalculated in kernel space'
complete -c memleak-bpfcc -l wa-missing-free -d 'Make up the action of free to alleviate misjudgments when free is missing'
complete -c memleak-bpfcc -s s -d 'Record roughly every SAMPLE_RATE-th allocation to reduce overhead'
complete -c memleak-bpfcc -s z -d 'Capture only allocations that are larger than or equal to MIN_SIZE bytes'
complete -c memleak-bpfcc -s Z -d 'Capture only allocations that are smaller than or equal to MAX_SIZE bytes'
complete -c memleak-bpfcc -s O -d 'Attach to allocation functions in specified object instead of resolving libc'

