# netplan-apply
# Autogenerated from man page /usr/share/man/man8/netplan-apply.8.gz
complete -c netplan-apply -s h -l help -d 'Print basic help'
complete -c netplan-apply -l debug -d 'Print debugging output during the process.  KNOWN ISSUES'

