# netplan-set
# Autogenerated from man page /usr/share/man/man8/netplan-set.8.gz
complete -c netplan-set -s h -l help -d 'Print basic help'
complete -c netplan-set -l debug -d 'Print debugging output during the process'
complete -c netplan-set -l root-dir -d 'Write YAML files into this root instead of /'
complete -c netplan-set -l origin-hint -d 'Specify a name for the config file, e. g'

