# netplan-try
# Autogenerated from man page /usr/share/man/man8/netplan-try.8.gz
complete -c netplan-try -s h -l help -d 'Print basic help'
complete -c netplan-try -l debug -d 'Print debugging output during the process'
complete -c netplan-try -l config-file -d 'In addition to the usual configuration, apply \\f[I]CONFIG_FILE\\f[R]'
complete -c netplan-try -l timeout -d 'Wait for TIMEOUT seconds before reverting.  Defaults to 120 seconds'

