# netplan-get
# Autogenerated from man page /usr/share/man/man8/netplan-get.8.gz
complete -c netplan-get -s h -l help -d 'Print basic help'
complete -c netplan-get -l debug -d 'Print debugging output during the process'
complete -c netplan-get -l root-dir -d 'Read YAML files from this root instead of / SEE ALSO'

