# netplan-generate
# Autogenerated from man page /usr/share/man/man8/netplan-generate.8.gz
complete -c netplan-generate -s h -l help -d 'Print basic help'
complete -c netplan-generate -l debug -d 'Print debugging output during the process'
complete -c netplan-generate -l root-dir -d 'Instead of looking in /{lib,etc,run}/netplan, look in /\\f[I]ROOT_DIR\\f[R]/{li…'
complete -c netplan-generate -l mapping -d 'Instead of generating output files, parse the configuration files and print s…'

