# netplan-dbus
# Autogenerated from man page /usr/share/man/man8/netplan-dbus.8.gz
complete -c netplan-dbus -l root-dir -d 'config of the the given config object[aq]s state [bu] 2 Set(s:CONFIG_DELTA, s…'

