# netqtop-bpfcc
# Autogenerated from man page /usr/share/man/man8/netqtop-bpfcc.8.gz
complete -c netqtop-bpfcc -s n -d 'Specify the network interface card'
complete -c netqtop-bpfcc -s i -d 'Print results every INTERVAL seconds.  The default value is 1'
complete -c netqtop-bpfcc -s t -d 'Print BPS and PPS of each queue.  EXAMPLES'

