# nfsslower-bpfcc
# Autogenerated from man page /usr/share/man/man8/nfsslower-bpfcc.8.gz
complete -c nfsslower-bpfcc -s j -d 'Trace output in CSV format'
complete -c nfsslower-bpfcc -s p -d 'Trace this PID only'

