# offcputime-bpfcc
# Autogenerated from man page /usr/share/man/man8/offcputime-bpfcc.8.gz
complete -c offcputime-bpfcc -s h -d 'Print usage message'
complete -c offcputime-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c offcputime-bpfcc -s t -d 'Trace this thread ID only (filtered in-kernel)'
complete -c offcputime-bpfcc -s u -d 'Only trace user threads (no kernel threads)'
complete -c offcputime-bpfcc -s k -d 'Only trace kernel threads (no user threads)'
complete -c offcputime-bpfcc -s U -d 'Show stacks from user space only (no kernel space stacks)'
complete -c offcputime-bpfcc -s K -d 'Show stacks from kernel space only (no user space stacks)'
complete -c offcputime-bpfcc -s d -d 'Insert delimiter between kernel/user stacks'
complete -c offcputime-bpfcc -s f -d 'Print output in folded stack format'
complete -c offcputime-bpfcc -l stack-storage-size -d 'Change the number of unique stack traces that can be stored and displayed'
complete -c offcputime-bpfcc -s m -d 'The minimum time in microseconds over which we store traces (default 1)'
complete -c offcputime-bpfcc -s M -d 'The maximum time in microseconds under which we store traces (default U64_MAX)'
complete -c offcputime-bpfcc -l state -d 'Filter on this thread state bitmask (eg, 2 == TASK_UNINTERRUPTIBLE)'

