# opensnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/opensnoop-bpfcc.8.gz
complete -c opensnoop-bpfcc -s h -d 'Print usage message'
complete -c opensnoop-bpfcc -s T -d 'Include a timestamp column'
complete -c opensnoop-bpfcc -s U -d 'Show UID'
complete -c opensnoop-bpfcc -s x -d 'Only print failed opens'
complete -c opensnoop-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c opensnoop-bpfcc -s t -d 'Trace this thread ID only (filtered in-kernel)'
complete -c opensnoop-bpfcc -s u -d 'Trace this UID only (filtered in-kernel)'
complete -c opensnoop-bpfcc -s d -d 'Total duration of trace in seconds'
complete -c opensnoop-bpfcc -s n -d 'Only print processes where its name partially matches \'name\''
complete -c opensnoop-bpfcc -s e -d 'Show extended fields'
complete -c opensnoop-bpfcc -s f -d 'Filter on open() flags, e. g. , O_WRONLY'
complete -c opensnoop-bpfcc -l cgroupmap -d 'Trace cgroups in this BPF map only (filtered in-kernel)'
complete -c opensnoop-bpfcc -l mntnsmap -d 'Trace mount namespaces in this BPF map only (filtered in-kernel).  EXAMPLES'

