# pcre-config
# Autogenerated from man page /usr/share/man/man1/pcre-config.1.gz
complete -c pcre-config -l prefix -d 'Writes the directory prefix used in the PCRE installation for architecture in…'
complete -c pcre-config -l exec-prefix -d 'Writes the directory prefix used in the PCRE installation for architecture de…'
complete -c pcre-config -l version -d 'Writes the version of PCRE installed to standard output'
complete -c pcre-config -l libs -d 'Writes to standard output the command line options required to link with PCRE…'
complete -c pcre-config -l libs-posix -d 'Writes to standard output the command line options required to link with the …'
complete -c pcre-config -l cflags -d 'Writes to standard output the command line options required to compile  files…'
complete -c pcre-config -l cflags-posix -d 'Writes to standard output the command line options required to compile files …'

