# popsicle
# Autogenerated from man page /usr/share/man/man1/popsicle.1.gz
complete -c popsicle -s a -l all -d 'Flash all detected USB drives'
complete -c popsicle -s c -l check -d 'Check if written image matches source image'
complete -c popsicle -s u -l unmount -d 'Unmount mounted devices'
complete -c popsicle -s y -l yes -d 'Continue without confirmation'
complete -c popsicle -s h -l help -d 'Print help'
complete -c popsicle -s V -l version -d 'Print version'

