# profile-bpfcc
# Autogenerated from man page /usr/share/man/man8/profile-bpfcc.8.gz
complete -c profile-bpfcc -s h -d 'Print usage message'
complete -c profile-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c profile-bpfcc -s L -d 'Trace this thread ID only (filtered in-kernel)'
complete -c profile-bpfcc -s F -d 'Frequency to sample stacks'
complete -c profile-bpfcc -s c -d 'Sample stacks every one in this many events'
complete -c profile-bpfcc -s f -d 'Print output in folded stack format'
complete -c profile-bpfcc -s d -d 'Include an output delimiter between kernel and user stacks (either "--", or, …'
complete -c profile-bpfcc -s U -d 'Show stacks from user space only (no kernel space stacks)'
complete -c profile-bpfcc -s K -d 'Show stacks from kernel space only (no user space stacks)'
complete -c profile-bpfcc -s I -d 'Include CPU idle stacks (by default these are excluded)'
complete -c profile-bpfcc -l stack-storage-size -d 'The maximum number of unique stack traces that the kernel will count (default…'
complete -c profile-bpfcc -s C -d 'Collect stacks only from specified cpu'
complete -c profile-bpfcc -l cgroupmap -d 'Profile cgroups in this BPF map only (filtered in-kernel)'

