# pythoncalls-bpfcc
# Autogenerated from man page /usr/share/man/man8/pythoncalls-bpfcc.8.gz
complete -c pythoncalls-bpfcc -s l -d 'The language to trace'
complete -c pythoncalls-bpfcc -s T -d 'Print only the top methods by frequency or latency'
complete -c pythoncalls-bpfcc -s L -d 'Collect method invocation latency (duration)'
complete -c pythoncalls-bpfcc -s S -d 'Collect Linux syscalls frequency and timing'
complete -c pythoncalls-bpfcc -s v -d 'Print the resulting BPF program, for debugging purposes'
complete -c pythoncalls-bpfcc -s m -d 'Print times in milliseconds (the default is microseconds)'

