# readahead-bpfcc
# Autogenerated from man page /usr/share/man/man8/readahead-bpfcc.8.gz
complete -c readahead-bpfcc -s h -d 'Print usage message'
complete -c readahead-bpfcc -s d -d 'Trace the read-ahead caching system for DURATION seconds  EXAMPLES'

