# reset-trace-bpfcc
# Autogenerated from man page /usr/share/man/man8/reset-trace-bpfcc.8.gz
complete -c reset-trace-bpfcc -s F -d Force
complete -c reset-trace-bpfcc -s h -d 'USAGE message'
complete -c reset-trace-bpfcc -s q -d 'Quiet.  No output while working'
complete -c reset-trace-bpfcc -s v -d 'Verbose: print what it is doing.  EXAMPLES'

