# rubyobjnew-bpfcc
# Autogenerated from man page /usr/share/man/man8/rubyobjnew-bpfcc.8.gz
complete -c rubyobjnew-bpfcc -s C -d 'Print the top object types sorted by number of instances'
complete -c rubyobjnew-bpfcc -s S -d 'Print the top object types sorted by size'
complete -c rubyobjnew-bpfcc -s v -d 'Print the resulting BPF program, for debugging purposes'

