# rubygc-bpfcc
# Autogenerated from man page /usr/share/man/man8/rubygc-bpfcc.8.gz
complete -c rubygc-bpfcc -s v -d 'Print the resulting BPF program, for debugging purposes'
complete -c rubygc-bpfcc -s m -d 'Print times in milliseconds.  The default is microseconds'
complete -c rubygc-bpfcc -s M -d 'Display only collections that are longer than this threshold'
complete -c rubygc-bpfcc -s F -d 'Display only collections whose textual description matches (contains) this st…'

