# runqlen-bpfcc
# Autogenerated from man page /usr/share/man/man8/runqlen-bpfcc.8.gz
complete -c runqlen-bpfcc -s h -d 'Print usage message'
complete -c runqlen-bpfcc -s T -d 'Include timestamps on output'
complete -c runqlen-bpfcc -s O -d 'Report run queue occupancy'
complete -c runqlen-bpfcc -s C -d 'Report for each CPU'

