# runqslower-bpfcc
# Autogenerated from man page /usr/share/man/man8/runqslower-bpfcc.8.gz
complete -c runqslower-bpfcc -s h -d 'Print usage message'
complete -c runqslower-bpfcc -s p -d 'Only show this PID (filtered in kernel for efficiency)'
complete -c runqslower-bpfcc -s t -d 'Only show this TID (filtered in kernel for efficiency)'

