# runqlat-bpfcc
# Autogenerated from man page /usr/share/man/man8/runqlat-bpfcc.8.gz
complete -c runqlat-bpfcc -s h -d 'Print usage message'
complete -c runqlat-bpfcc -s T -d 'Include timestamps on output'
complete -c runqlat-bpfcc -s m -d 'Output histogram in milliseconds'
complete -c runqlat-bpfcc -s P -d 'Print a histogram for each PID'
complete -c runqlat-bpfcc -l pidnss -d 'Print a histogram for each PID namespace (short for PID namespaces)'
complete -c runqlat-bpfcc -s L -d 'Print a histogram for each thread ID'
complete -c runqlat-bpfcc -s p -d 'Only show this PID (filtered in kernel for efficiency)'

