# shmsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/shmsnoop-bpfcc.8.gz
complete -c shmsnoop-bpfcc -s h -d 'Print usage message'
complete -c shmsnoop-bpfcc -s T -d 'Include a timestamp column'
complete -c shmsnoop-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c shmsnoop-bpfcc -s t -d 'Trace this thread ID only (filtered in-kernel)'
complete -c shmsnoop-bpfcc -s d -d 'Total duration of trace in seconds'
complete -c shmsnoop-bpfcc -s n -d 'Only print command lines matching this command name (regex) EXAMPLES'

