# slabratetop-bpfcc
# Autogenerated from man page /usr/share/man/man8/slabratetop-bpfcc.8.gz
complete -c slabratetop-bpfcc -s C -d 'Don\'t clear the screen'
complete -c slabratetop-bpfcc -s r -d 'Maximum number of rows to print.  Default is 20'

