# sofdsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/sofdsnoop-bpfcc.8.gz
complete -c sofdsnoop-bpfcc -s h -l help -d 'show this help message and exit'
complete -c sofdsnoop-bpfcc -s T -l timestamp -d 'include timestamp on output'
complete -c sofdsnoop-bpfcc -s p -l pid -d 'trace this PID only'
complete -c sofdsnoop-bpfcc -s t -l tid -d 'trace this TID only'
complete -c sofdsnoop-bpfcc -s n -l name -d 'only print process names containing this name'
complete -c sofdsnoop-bpfcc -s d -l duration -d 'total duration of trace in seconds EXAMPLES'

