# solisten-bpfcc
# Autogenerated from man page /usr/share/man/man8/solisten-bpfcc.8.gz
complete -c solisten-bpfcc -s h -l help -d 'show this help message and exit'
complete -c solisten-bpfcc -l show-netns -d 'show network namespace'
complete -c solisten-bpfcc -s p -l pid -d 'trace this PID only'
complete -c solisten-bpfcc -s n -l netns -d 'trace this Network Namespace only EXAMPLES'

