# stackcount-bpfcc
# Autogenerated from man page /usr/share/man/man8/stackcount-bpfcc.8.gz
complete -c stackcount-bpfcc -s h -d 'Print usage message'
complete -c stackcount-bpfcc -s r -d 'Allow regular expressions for the search pattern'
complete -c stackcount-bpfcc -s s -d 'Show address offsets'
complete -c stackcount-bpfcc -s P -d 'Display stacks separately for each process'
complete -c stackcount-bpfcc -s K -d 'Show kernel stack only'
complete -c stackcount-bpfcc -s U -d 'Show user stack only'
complete -c stackcount-bpfcc -s T -d 'Include a timestamp with interval output'
complete -c stackcount-bpfcc -s v -d 'Show raw addresses'
complete -c stackcount-bpfcc -s d -d 'Print a delimiter ("--") in-between the kernel and user stacks'
complete -c stackcount-bpfcc -l debug -d 'Print the source of the BPF program when loading it (for debugging purposes)'
complete -c stackcount-bpfcc -s i -d 'Summary interval, in seconds'
complete -c stackcount-bpfcc -s D -d 'Total duration of trace, in seconds.  -f Folded output format'
complete -c stackcount-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c stackcount-bpfcc -s c -d 'Trace this CPU only (filtered in-kernel)'
complete -c stackcount-bpfcc -s f -d 'Folded output format'

