# statsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/statsnoop-bpfcc.8.gz
complete -c statsnoop-bpfcc -s h -d 'Print usage message'
complete -c statsnoop-bpfcc -s t -d 'Include a timestamp column: in seconds since the first event, with decimal pl…'
complete -c statsnoop-bpfcc -s x -d 'Only print failed stats'
complete -c statsnoop-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel).  EXAMPLES'

