# sync-available
# Autogenerated from man page /usr/share/man/man8/sync-available.8.gz
complete -c sync-available -l version -d 'Output the name and version of the program onto standard output stream'
complete -c sync-available -l help -d 'Give a brief usage statement on the standard output stream'

