# syscount-bpfcc
# Autogenerated from man page /usr/share/man/man8/syscount-bpfcc.8.gz
complete -c syscount-bpfcc -s h -d 'Print usage message'
complete -c syscount-bpfcc -s p -d 'Trace only this process'
complete -c syscount-bpfcc -s i -d 'Print the summary at the specified interval (in seconds)'
complete -c syscount-bpfcc -s d -d 'Total duration of trace (in seconds)'
complete -c syscount-bpfcc -s T -d 'Print only this many entries.  Default: 10'
complete -c syscount-bpfcc -s x -d 'Trace only failed syscalls (i. e'
complete -c syscount-bpfcc -s e -d 'Trace only syscalls that failed with that error (e. g.  -e EPERM or -e 1)'
complete -c syscount-bpfcc -s m -d 'Display times in milliseconds.  Default: microseconds'
complete -c syscount-bpfcc -s P -d 'Summarize by process and not by syscall'
complete -c syscount-bpfcc -s l -d 'List the syscalls recognized by the tool (hard-coded list)'

