# tbl-dctrl
# Autogenerated from man page /usr/share/man/man1/tbl-dctrl.1.gz
complete -c tbl-dctrl -s d -l delimiter -d 'Instead of drawing nice borders to the table, use the specified  delimiter st…'
complete -c tbl-dctrl -s H -l no-heading -d 'Do not print a table heading (column titles)'
complete -c tbl-dctrl -s l -l errorlevel -d 'Set log level to R level '
complete -c tbl-dctrl -s V -l version -d 'Print out version information'
complete -c tbl-dctrl -s C -l copying -d 'Print out the copyright license'
complete -c tbl-dctrl -s c -l column -d 'switch with a column specification'
complete -c tbl-dctrl -s h -l help -d 'Print out a help summary'

