# tclobjnew-bpfcc
# Autogenerated from man page /usr/share/man/man8/tclobjnew-bpfcc.8.gz
complete -c tclobjnew-bpfcc -s C -d 'Print the top object types sorted by number of instances'
complete -c tclobjnew-bpfcc -s S -d 'Print the top object types sorted by size'
complete -c tclobjnew-bpfcc -s v -d 'Print the resulting BPF program, for debugging purposes'

