# tcpaccept-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcpaccept-bpfcc.8.gz
complete -c tcpaccept-bpfcc -s h -d 'Print usage message'
complete -c tcpaccept-bpfcc -s T -d 'Include a time column on output (HH:MM:SS)'
complete -c tcpaccept-bpfcc -s t -d 'Include a timestamp column'
complete -c tcpaccept-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c tcpaccept-bpfcc -s P -d 'Comma-separated list of local ports to trace (filtered in-kernel)'
complete -c tcpaccept-bpfcc -l cgroupmap -d 'Trace cgroups in this BPF map only (filtered in-kernel)'
complete -c tcpaccept-bpfcc -l mntnsmap -d 'Trace mount namespaces in this BPF map only (filtered in-kernel).  EXAMPLES'

