# tcpconnect-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcpconnect-bpfcc.8.gz
complete -c tcpconnect-bpfcc -s h -d 'Print usage message'
complete -c tcpconnect-bpfcc -s t -d 'Include a timestamp column'
complete -c tcpconnect-bpfcc -s c -d 'Count connects per src ip and dest ip/port'
complete -c tcpconnect-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c tcpconnect-bpfcc -s P -d 'Comma-separated list of destination ports to trace (filtered in-kernel)'
complete -c tcpconnect-bpfcc -s U -d 'Include a UID column'
complete -c tcpconnect-bpfcc -s u -d 'Trace this UID only (filtered in-kernel)'
complete -c tcpconnect-bpfcc -l cgroupmap -d 'Trace cgroups in this BPF map only (filtered in-kernel)'
complete -c tcpconnect-bpfcc -l mntnsmap -d 'Trace mount namespaces in this BPF map only (filtered in-kernel)'
complete -c tcpconnect-bpfcc -s d -d 'Shows the most recent DNS query for the IP address in the connect call'

