# tcplife-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcplife-bpfcc.8.gz
complete -c tcplife-bpfcc -s h -d 'Print usage message'
complete -c tcplife-bpfcc -s s -d 'Comma separated values output (parseable)'
complete -c tcplife-bpfcc -s t -d 'Include a timestamp column (seconds)'
complete -c tcplife-bpfcc -s T -d 'Include a time column (HH:MM:SS)'
complete -c tcplife-bpfcc -s w -d 'Wide column output (fits IPv6 addresses)'
complete -c tcplife-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c tcplife-bpfcc -s L -d 'Comma-separated list of local ports to trace (filtered in-kernel)'
complete -c tcplife-bpfcc -s D -d 'Comma-separated list of destination ports to trace (filtered in-kernel)'

