# tcpretrans-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcpretrans-bpfcc.8.gz
complete -c tcpretrans-bpfcc -s h -d 'Print usage message'
complete -c tcpretrans-bpfcc -s l -d 'Include tail loss probe attempts (in some cases the kernel may not complete t…'
complete -c tcpretrans-bpfcc -s c -d 'Count occurring retransmits per flow.   EXAMPLES'

