# tcprtt-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcprtt-bpfcc.8.gz
complete -c tcprtt-bpfcc -s h -d 'Print usage message'
complete -c tcprtt-bpfcc -s T -d 'Include a time column on output (HH:MM:SS)'
complete -c tcprtt-bpfcc -s D -d 'Show debug infomation of bpf text'
complete -c tcprtt-bpfcc -s m -d 'Output histogram in milliseconds'
complete -c tcprtt-bpfcc -s i -d 'Print output every interval seconds'
complete -c tcprtt-bpfcc -s d -d 'Total duration of trace in seconds'
complete -c tcprtt-bpfcc -s p -d 'Filter for local port'
complete -c tcprtt-bpfcc -s P -d 'Filter for remote port'
complete -c tcprtt-bpfcc -s a -d 'Filter for local address'
complete -c tcprtt-bpfcc -s A -d 'Filter for remote address'
complete -c tcprtt-bpfcc -s b -d 'Show sockets histogram by local address'
complete -c tcprtt-bpfcc -s B -d 'Show sockets histogram by remote address.  EXAMPLES'

