# tcpstates-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcpstates-bpfcc.8.gz
complete -c tcpstates-bpfcc -s h -d 'Print usage message'
complete -c tcpstates-bpfcc -s s -d 'Comma separated values output (parseable)'
complete -c tcpstates-bpfcc -s t -d 'Include a timestamp column (seconds)'
complete -c tcpstates-bpfcc -s T -d 'Include a time column (HH:MM:SS)'
complete -c tcpstates-bpfcc -s w -d 'Wide column output (fits IPv6 addresses)'
complete -c tcpstates-bpfcc -s L -d 'Comma-separated list of local ports to trace (filtered in-kernel)'
complete -c tcpstates-bpfcc -s D -d 'Comma-separated list of destination ports to trace (filtered in-kernel)'
complete -c tcpstates-bpfcc -s Y -d 'Log session state changes to the systemd journal.  EXAMPLES'

