# tcpsubnet-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcpsubnet-bpfcc.8.gz
complete -c tcpsubnet-bpfcc -s h -d 'Print USAGE message'
complete -c tcpsubnet-bpfcc -s v -d 'Run in verbose mode.  Will output subnet evaluation and the BPF program'
complete -c tcpsubnet-bpfcc -s J -d 'Format output in JSON'
complete -c tcpsubnet-bpfcc -s i -d 'Interval between updates, seconds (default 1)'
complete -c tcpsubnet-bpfcc -s f -d 'Format output units.  Supported values are bkmBKM'
complete -c tcpsubnet-bpfcc -l ebpf -d 'Prints the BPF program'

