# tcptracer-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcptracer-bpfcc.8.gz
complete -c tcptracer-bpfcc -s h -d 'Print usage message'
complete -c tcptracer-bpfcc -s v -d 'Print full lines, with long event type names and network namespace numbers'
complete -c tcptracer-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c tcptracer-bpfcc -s N -d 'Trace this network namespace only (filtered in-kernel)'
complete -c tcptracer-bpfcc -l cgroupmap -d 'Trace cgroups in this BPF map only (filtered in-kernel)'
complete -c tcptracer-bpfcc -l mntnsmap -d 'Trace mount namespaces in the map (filtered in-kernel).  EXAMPLES'

