# tcptop-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcptop-bpfcc.8.gz
complete -c tcptop-bpfcc -s h -d 'Print USAGE message'
complete -c tcptop-bpfcc -s C -d 'Don\'t clear the screen'
complete -c tcptop-bpfcc -s S -d 'Don\'t print the system summary line (load averages)'
complete -c tcptop-bpfcc -s p -d 'Trace this PID only'
complete -c tcptop-bpfcc -l cgroupmap -d 'Trace cgroups in this BPF map only (filtered in-kernel)'
complete -c tcptop-bpfcc -l mntnsmap -d 'Trace mount namespaces in this BPF map only (filtered in-kernel)'

