# tplist-bpfcc
# Autogenerated from man page /usr/share/man/man8/tplist-bpfcc.8.gz
complete -c tplist-bpfcc -s p -d 'Display the USDT probes from all the libraries loaded by the specified process'
complete -c tplist-bpfcc -s l -d 'Display the USDT probes from the specified library or executable'
complete -c tplist-bpfcc -s v -d 'Increase the verbosity level'

