# ucalls
# Autogenerated from man page /usr/share/man/man8/ucalls.8.gz
complete -c ucalls -s l -d 'The language to trace'
complete -c ucalls -s T -d 'Print only the top methods by frequency or latency'
complete -c ucalls -s L -d 'Collect method invocation latency (duration)'
complete -c ucalls -s S -d 'Collect Linux syscalls frequency and timing'
complete -c ucalls -s v -d 'Print the resulting BPF program, for debugging purposes'
complete -c ucalls -s m -d 'Print times in milliseconds (the default is microseconds)'

