# uflow
# Autogenerated from man page /usr/share/man/man8/uflow.8.gz
complete -c uflow -s M -d 'Print only method calls where the method name begins with this string'
complete -c uflow -s C -d 'Print only method calls where the class name begins with this string'
complete -c uflow -s v -d 'Print the resulting BPF program, for debugging purposes'

