# ugc
# Autogenerated from man page /usr/share/man/man8/ugc.8.gz
complete -c ugc -s v -d 'Print the resulting BPF program, for debugging purposes'
complete -c ugc -s m -d 'Print times in milliseconds.  The default is microseconds'
complete -c ugc -s M -d 'Display only collections that are longer than this threshold'
complete -c ugc -s F -d 'Display only collections whose textual description matches (contains) this st…'

