# uobjnew
# Autogenerated from man page /usr/share/man/man8/uobjnew.8.gz
complete -c uobjnew -s C -d 'Print the top object types sorted by number of instances'
complete -c uobjnew -s S -d 'Print the top object types sorted by size'
complete -c uobjnew -s v -d 'Print the resulting BPF program, for debugging purposes'

