# ustat
# Autogenerated from man page /usr/share/man/man8/ustat.8.gz
complete -c ustat -s l -d 'The language to trace.  By default, all languages are traced'
complete -c ustat -s C -d 'Do not clear the screen between updates'
complete -c ustat -s S -d 'Sort the output by the specified field'
complete -c ustat -s r -d 'Do not print more than this number of rows'
complete -c ustat -s d -d 'Print the resulting BPF program, for debugging purposes'

