# uthreads
# Autogenerated from man page /usr/share/man/man8/uthreads.8.gz
complete -c uthreads -s l -d 'The language to trace'
complete -c uthreads -s v -d 'Print the resulting BPF program, for debugging purposes'

