# wakeuptime-bpfcc
# Autogenerated from man page /usr/share/man/man8/wakeuptime-bpfcc.8.gz
complete -c wakeuptime-bpfcc -s h -d 'Print usage message'
complete -c wakeuptime-bpfcc -s f -d 'Print output in folded stack format'
complete -c wakeuptime-bpfcc -s u -d 'Only trace user threads (not kernel threads)'
complete -c wakeuptime-bpfcc -s v -d 'Show raw addresses (for non-folded format)'
complete -c wakeuptime-bpfcc -s p -d 'Trace this process ID only (filtered in-kernel)'
complete -c wakeuptime-bpfcc -l stack-storage-size -d 'Change the number of unique stack traces that can be stored and displayed'
complete -c wakeuptime-bpfcc -s m -d 'The amount of time in microseconds over which we store traces (default 1)'
complete -c wakeuptime-bpfcc -s M -d 'The amount of time in microseconds under which we store traces (default U64_M…'

