# zfsdist-bpfcc
# Autogenerated from man page /usr/share/man/man8/zfsdist-bpfcc.8.gz
complete -c zfsdist-bpfcc -s h -d 'Print usage message'
complete -c zfsdist-bpfcc -s T -d 'Don\'t include timestamps on interval output'
complete -c zfsdist-bpfcc -s m -d 'Output in milliseconds'
complete -c zfsdist-bpfcc -s p -d 'Trace this PID only.  EXAMPLES'

